services:
  localstack:
    container_name: "locastack-init"
    image: localstack/localstack:3.1
    ports:
      - 4566:4566
    environment:
      - DEBUG=1
      - SERVICES=s3,sns,sqs
    volumes:
      - ./init/init.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./local-fixtures:/fixtures